### ─────────────────────────────── General ───────────────────────────────
seed: 39                 # torch / numpy seed
device: cuda             # cuda | cpu
output_dir: output_timer

### ────────────────────────────── HuggingFace ────────────────────────────
quantization: none        # 4bit | 8bit | none

### ─────────────────────────────── Model ────────────────────────────────
model_name: NousResearch/Nous-Hermes-2-Mistral-7B-DPO


### ─────────────────────────────── Data  ────────────────────────────────
max_sample_size: 4000
n_train_proportion: 0.6
n_val_proportion:   0.2
n_test_proportion:  0.2

### ───────────────────────────── Benchmarks ─────────────────────────────

benchmarks:               # any subset of the implemented loaders
    # - DisabilityStatus
    - GenderIdentity
    # - Nationality
    # - PhysicalAppearance
    # - RaceEthnicity
    # - RaceXGender
    # - RaceXSES
    # - Religion
    # - SES
    # - SexualOrientation
    # - ETHICS_Commonsense
    # - ETHICS_Deontology
    # - ETHICS_Justice
    # - Sycophancy
    # - TruthfulQA

# # benchmarks:               # any subset of the implemented loaders
#     - OpenBookQA
#     - ARCChallenge
#     - LSAT

### ─────────────────────────── Steering Search ──────────────────────────
layers_to_try:  [16]
steer_strengths: [1]
methods:                 # leave out any you don't want
  - iBAS_wrong_only
steer_target:  residual