### ─────────────────────────────── General ───────────────────────────────
seed: 0                 # torch / numpy seed
device: cuda             # cuda | cpu
output_dir: output_devel

### ────────────────────────────── HuggingFace ────────────────────────────
quantization: none        # 4bit | 8bit | none

### ─────────────────────────────── Model ────────────────────────────────
model_name: TinyLlama/TinyLlama-1.1B-Chat-v1.0
# TinyLlama/TinyLlama-1.1B-Chat-v1.0
# mistralai/Mistral-7B-Instruct-v0.3
# meta-llama/Llama-3.1-8B-Instruct
# mistralai/Mixtral-8x7B-Instruct-v0.1
# NousResearch/Nous-Hermes-2-Mistral-7B-DPO
# google/gemma-7b-it
# deepseek-ai/deepseek-llm-7b-chat
# deepseek-ai/deepseek-coder-7b-instruct-v1.5
# deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
# deepseek-ai/DeepSeek-R1-Distill-Llama-8B
# Qwen/Qwen2.5-7B-Instruct


### ─────────────────────────────── Data  ────────────────────────────────

max_sample_size: 100
n_train_proportion: 0.6
n_val_proportion:   0.2
n_test_proportion:  0.2

### ───────────────────────────── Benchmarks ─────────────────────────────

benchmarks:               # any subset of the implemented loaders
    - DisabilityStatus
    - GenderIdentity
    - Nationality
    - PhysicalAppearance
    - RaceEthnicity
    - RaceXGender
    - RaceXSES
    - Religion
    - SES
    - SexualOrientation
    - ETHICS_Commonsense
    - ETHICS_Deontology
    - ETHICS_Justice
    - Sycophancy
    - TruthfulQA


### ─────────────────────────── Steering Search ──────────────────────────
layers_to_try:  [5, 16]
steer_strengths: [2.0, 32.0]

methods:                 
    - iBAS_all
    - iBAS_wrong_only
    - BAS_full_mcq

steer_target: residual

